# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f154c9b66271dc3f63cfbe80f3087c0a61f2ead1f9f495e5ff1a2b41cb333380b7016c30ec9b447e2057a39fff1b7e6478d89e1973ad835dc43f77bc100c341

test:
  secret_key_base: c5b02e352e8971c1bb4d049ff16ceafe9fed1ef038c7cf49a9ef21ad8e0ba0fa16f3db1723735d569344daa8c3cc888f3bae9c67e09cee7ac90beb95803c4e24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
